---
version: 2
updates:

  # Npm
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/migrations/fixtures"
    schedule:
      interval: "daily"

  ## Go mod

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/kotsadm/operator"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/kurl_proxy"
    schedule:
      interval: "daily"

  ## Github Actions

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  ## Dockerfiles

  - package-ecosystem: "docker"
    directory: "/deploy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/kotsadm/operator/deploy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/deploy/minio"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/kurl_proxy/deploy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/migrations/deploy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/migrations/fixtures/deploy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/web/deploy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/actions/containers"
    schedule:
      interval: "weekly"
